export const STORAGE_KEY = "chatgptAgentsState";

export const AGENT_STATES = Object.freeze({
  QUEUED: "QUEUED",
  CREATING_TAB: "CREATING_TAB",
  WAITING_FOR_CHATGPT: "WAITING_FOR_CHATGPT",
  READY: "READY",
  INJECTING_PROMPT: "INJECTING_PROMPT",
  SUBMITTED: "SUBMITTED",
  GENERATING: "GENERATING",
  RESPONSE_READY: "RESPONSE_READY",
  EVALUATING: "EVALUATING",
  PAUSED: "PAUSED",
  NEEDS_USER: "NEEDS_USER",
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
  CANCELLED: "CANCELLED"
});

export const EXECUTION_MODES = Object.freeze({
  MANUAL: "manual",
  ASSISTED: "assisted",
  AUTO: "auto"
});

export const DEFAULT_SETTINGS = Object.freeze({
  defaultMode: EXECUTION_MODES.ASSISTED,
  maxConcurrentAgents: 3,
  maxAutoContinuations: 8
});

export const TERMINAL_AGENT_STATES = new Set([
  AGENT_STATES.COMPLETE,
  AGENT_STATES.ERROR,
  AGENT_STATES.CANCELLED
]);

export const MESSAGE_TYPES = Object.freeze({
  GET_STATE: "GET_STATE",
  IMPORT_TASK_PAYLOAD: "IMPORT_TASK_PAYLOAD",
  START_TASK: "START_TASK",
  CONTINUE_TASK: "CONTINUE_TASK",
  PAUSE_TASK: "PAUSE_TASK",
  CANCEL_TASK: "CANCEL_TASK",
  OPEN_TASK_TAB: "OPEN_TASK_TAB",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  PAUSE_ALL: "PAUSE_ALL",
  RESUME_ALL: "RESUME_ALL",
  CHATGPT_PAGE_READY: "CHATGPT_PAGE_READY",
  CHATGPT_RESPONSE: "CHATGPT_RESPONSE",
  CHATGPT_GENERATING: "CHATGPT_GENERATING",
  INJECT_PROMPT: "INJECT_PROMPT",
  STOP_GENERATION: "STOP_GENERATION",
  GET_CHAT_STATE: "GET_CHAT_STATE"
});
