export const STORAGE_KEY = "chatgptAgentsState";

export const AGENT_STATES = Object.freeze({
  QUEUED: "QUEUED",
  CREATING_TAB: "CREATING_TAB",
  WAITING_FOR_CHATGPT: "WAITING_FOR_CHATGPT",
  READY: "READY",
  INJECTING_PROMPT: "INJECTING_PROMPT",
  SUBMITTED: "SUBMITTED",
  GENERATING: "GENERATING",
  RESPONSE_READY: "RESPONSE_READY",
  EVALUATING: "EVALUATING",
  BROWSER_ACTING: "BROWSER_ACTING",
  PAUSED: "PAUSED",
  NEEDS_USER: "NEEDS_USER",
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
  CANCELLED: "CANCELLED"
});

export const EXECUTION_MODES = Object.freeze({
  MANUAL: "manual",
  ASSISTED: "assisted",
  AUTO: "auto"
});

export const DEFAULT_SETTINGS = Object.freeze({
  defaultMode: EXECUTION_MODES.AUTO,
  maxConcurrentAgents: 1,
  maxAutoContinuations: 40,
  visualMouse: true
});

export const TERMINAL_AGENT_STATES = new Set([
  AGENT_STATES.COMPLETE,
  AGENT_STATES.ERROR,
  AGENT_STATES.CANCELLED
]);

export const MESSAGE_TYPES = Object.freeze({
  GET_STATE: "GET_STATE",
  IMPORT_TASK_PAYLOAD: "IMPORT_TASK_PAYLOAD",
  START_TASK: "START_TASK",
  CONTINUE_TASK: "CONTINUE_TASK",
  PAUSE_TASK: "PAUSE_TASK",
  CANCEL_TASK: "CANCEL_TASK",
  DELETE_TASK: "DELETE_TASK",
  OPEN_TASK_TAB: "OPEN_TASK_TAB",
  CAPTURE_TASK_EVIDENCE: "CAPTURE_TASK_EVIDENCE",
  START_TUTORIAL_RECORDING: "START_TUTORIAL_RECORDING",
  STOP_TUTORIAL_RECORDING: "STOP_TUTORIAL_RECORDING",
  TUTORIAL_RECORDING_READY: "TUTORIAL_RECORDING_READY",
  TUTORIAL_RECORDING_ERROR: "TUTORIAL_RECORDING_ERROR",
  OFFSCREEN_START_TUTORIAL_RECORDING: "OFFSCREEN_START_TUTORIAL_RECORDING",
  OFFSCREEN_STOP_TUTORIAL_RECORDING: "OFFSCREEN_STOP_TUTORIAL_RECORDING",
  OFFSCREEN_REVOKE_RECORDING_URL: "OFFSCREEN_REVOKE_RECORDING_URL",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  PAUSE_ALL: "PAUSE_ALL",
  RESUME_ALL: "RESUME_ALL",
  CHATGPT_PAGE_READY: "CHATGPT_PAGE_READY",
  CHATGPT_RESPONSE: "CHATGPT_RESPONSE",
  CHATGPT_GENERATING: "CHATGPT_GENERATING",
  INJECT_PROMPT: "INJECT_PROMPT",
  ATTACH_IMAGE: "ATTACH_IMAGE",
  STOP_GENERATION: "STOP_GENERATION",
  GET_CHAT_STATE: "GET_CHAT_STATE"
});
