export const STORAGE_KEY = "chatgptAgentsState";
export const MAX_CONCURRENT_AGENTS = 3;
export const DEFAULT_CONCURRENT_AGENTS = 1;

export function normalizeMaxConcurrentAgents(value, fallback = DEFAULT_CONCURRENT_AGENTS) {
  const parsed = Number(value);
  const normalized = Number.isFinite(parsed) ? Math.floor(parsed) : fallback;
  return Math.min(MAX_CONCURRENT_AGENTS, Math.max(1, normalized));
}

export const AGENT_STATES = Object.freeze({
  QUEUED: "QUEUED",
  CREATING_TAB: "CREATING_TAB",
  WAITING_FOR_CHATGPT: "WAITING_FOR_CHATGPT",
  READY: "READY",
  INJECTING_PROMPT: "INJECTING_PROMPT",
  SUBMITTED: "SUBMITTED",
  GENERATING: "GENERATING",
  RESPONSE_READY: "RESPONSE_READY",
  EVALUATING: "EVALUATING",
  BROWSER_ACTING: "BROWSER_ACTING",
  PAUSED: "PAUSED",
  NEEDS_USER: "NEEDS_USER",
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
  CANCELLED: "CANCELLED"
});

export const EXECUTION_MODES = Object.freeze({
  MANUAL: "manual",
  ASSISTED: "assisted",
  AUTO: "auto"
});

export const DEFAULT_SETTINGS = Object.freeze({
  defaultMode: EXECUTION_MODES.AUTO,
  maxConcurrentAgents: DEFAULT_CONCURRENT_AGENTS,
  maxAutoContinuations: 40,
  visualMouse: true,
  autoDetectTaskJson: true,
  autoImportDetectedTasks: true,
  autoStartDetectedTasks: false,
  hideCompletedTasks: false
});

export const TERMINAL_AGENT_STATES = new Set([
  AGENT_STATES.COMPLETE,
  AGENT_STATES.ERROR,
  AGENT_STATES.CANCELLED
]);

export const MESSAGE_TYPES = Object.freeze({
  GET_STATE: "GET_STATE",
  IMPORT_TASK_PAYLOAD: "IMPORT_TASK_PAYLOAD",
  TASK_JSON_CANDIDATES: "TASK_JSON_CANDIDATES",
  START_TASK: "START_TASK",
  CONTINUE_TASK: "CONTINUE_TASK",
  PAUSE_TASK: "PAUSE_TASK",
  CANCEL_TASK: "CANCEL_TASK",
  DELETE_TASK: "DELETE_TASK",
  OPEN_TASK_TAB: "OPEN_TASK_TAB",
  OPEN_BROWSER_TAB: "OPEN_BROWSER_TAB",
  CAPTURE_TASK_EVIDENCE: "CAPTURE_TASK_EVIDENCE",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  PAUSE_ALL: "PAUSE_ALL",
  RESUME_ALL: "RESUME_ALL",
  CHATGPT_PAGE_READY: "CHATGPT_PAGE_READY",
  CHATGPT_RESPONSE: "CHATGPT_RESPONSE",
  CHATGPT_GENERATING: "CHATGPT_GENERATING",
  CHATGPT_ERROR: "CHATGPT_ERROR",
  INJECT_PROMPT: "INJECT_PROMPT",
  ATTACH_IMAGE: "ATTACH_IMAGE",
  STOP_GENERATION: "STOP_GENERATION",
  GET_CHAT_STATE: "GET_CHAT_STATE"
});
